// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "initialize_padded_memory_16_10_0_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic initialize_padded_memory_16_10_0_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic initialize_padded_memory_16_10_0_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_ST_fsm_state1 = "1";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_ST_fsm_state2 = "10";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_ST_fsm_state3 = "100";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_ST_fsm_state4 = "1000";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_ST_fsm_state5 = "10000";
const sc_lv<32> initialize_padded_memory_16_10_0_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> initialize_padded_memory_16_10_0_s::ap_const_lv32_1 = "1";
const sc_lv<1> initialize_padded_memory_16_10_0_s::ap_const_lv1_0 = "0";
const sc_lv<32> initialize_padded_memory_16_10_0_s::ap_const_lv32_2 = "10";
const sc_lv<32> initialize_padded_memory_16_10_0_s::ap_const_lv32_3 = "11";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_const_lv5_0 = "00000";
const sc_lv<1> initialize_padded_memory_16_10_0_s::ap_const_lv1_1 = "1";
const sc_lv<4> initialize_padded_memory_16_10_0_s::ap_const_lv4_0 = "0000";
const sc_lv<32> initialize_padded_memory_16_10_0_s::ap_const_lv32_4 = "100";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_const_lv5_10 = "10000";
const sc_lv<5> initialize_padded_memory_16_10_0_s::ap_const_lv5_1 = "1";
const sc_lv<4> initialize_padded_memory_16_10_0_s::ap_const_lv4_A = "1010";
const sc_lv<4> initialize_padded_memory_16_10_0_s::ap_const_lv4_1 = "1";
const sc_lv<3> initialize_padded_memory_16_10_0_s::ap_const_lv3_0 = "000";
const bool initialize_padded_memory_16_10_0_s::ap_const_boolean_1 = true;

initialize_padded_memory_16_10_0_s::initialize_padded_memory_16_10_0_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln46_1_fu_164_p2);
    sensitive << ( add_ln46_reg_205 );
    sensitive << ( zext_ln46_3_fu_160_p1 );

    SC_METHOD(thread_add_ln46_fu_142_p2);
    sensitive << ( zext_ln46_2_fu_138_p1 );
    sensitive << ( zext_ln46_1_fu_126_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln41_fu_90_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln41_fu_90_p2 );

    SC_METHOD(thread_icmp_ln41_fu_90_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( m_0_reg_57 );

    SC_METHOD(thread_icmp_ln43_fu_106_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( x_0_reg_68 );

    SC_METHOD(thread_icmp_ln45_fu_148_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( y_0_reg_79 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( input_addr_reg_218 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln46_4_fu_169_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_input_r_d0);
    sensitive << ( input_r_q0 );
    sensitive << ( zext_ln46_reg_192 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_input_r_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_m_fu_96_p2);
    sensitive << ( m_0_reg_57 );

    SC_METHOD(thread_tmp_16_fu_118_p3);
    sensitive << ( x_0_reg_68 );

    SC_METHOD(thread_tmp_17_fu_130_p3);
    sensitive << ( x_0_reg_68 );

    SC_METHOD(thread_x_fu_112_p2);
    sensitive << ( x_0_reg_68 );

    SC_METHOD(thread_y_fu_154_p2);
    sensitive << ( y_0_reg_79 );

    SC_METHOD(thread_zext_ln46_1_fu_126_p1);
    sensitive << ( tmp_16_fu_118_p3 );

    SC_METHOD(thread_zext_ln46_2_fu_138_p1);
    sensitive << ( tmp_17_fu_130_p3 );

    SC_METHOD(thread_zext_ln46_3_fu_160_p1);
    sensitive << ( y_0_reg_79 );

    SC_METHOD(thread_zext_ln46_4_fu_169_p1);
    sensitive << ( add_ln46_1_fu_164_p2 );

    SC_METHOD(thread_zext_ln46_fu_102_p1);
    sensitive << ( m_0_reg_57 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln41_fu_90_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln43_fu_106_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln45_fu_148_p2 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "initialize_padded_memory_16_10_0_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_we0, "(port)input_r_we0");
    sc_trace(mVcdFile, input_r_d0, "(port)input_r_d0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, m_fu_96_p2, "m_fu_96_p2");
    sc_trace(mVcdFile, m_reg_187, "m_reg_187");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln46_fu_102_p1, "zext_ln46_fu_102_p1");
    sc_trace(mVcdFile, zext_ln46_reg_192, "zext_ln46_reg_192");
    sc_trace(mVcdFile, icmp_ln41_fu_90_p2, "icmp_ln41_fu_90_p2");
    sc_trace(mVcdFile, x_fu_112_p2, "x_fu_112_p2");
    sc_trace(mVcdFile, x_reg_200, "x_reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln46_fu_142_p2, "add_ln46_fu_142_p2");
    sc_trace(mVcdFile, add_ln46_reg_205, "add_ln46_reg_205");
    sc_trace(mVcdFile, icmp_ln43_fu_106_p2, "icmp_ln43_fu_106_p2");
    sc_trace(mVcdFile, y_fu_154_p2, "y_fu_154_p2");
    sc_trace(mVcdFile, y_reg_213, "y_reg_213");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, input_addr_reg_218, "input_addr_reg_218");
    sc_trace(mVcdFile, icmp_ln45_fu_148_p2, "icmp_ln45_fu_148_p2");
    sc_trace(mVcdFile, m_0_reg_57, "m_0_reg_57");
    sc_trace(mVcdFile, x_0_reg_68, "x_0_reg_68");
    sc_trace(mVcdFile, y_0_reg_79, "y_0_reg_79");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, zext_ln46_4_fu_169_p1, "zext_ln46_4_fu_169_p1");
    sc_trace(mVcdFile, tmp_16_fu_118_p3, "tmp_16_fu_118_p3");
    sc_trace(mVcdFile, tmp_17_fu_130_p3, "tmp_17_fu_130_p3");
    sc_trace(mVcdFile, zext_ln46_2_fu_138_p1, "zext_ln46_2_fu_138_p1");
    sc_trace(mVcdFile, zext_ln46_1_fu_126_p1, "zext_ln46_1_fu_126_p1");
    sc_trace(mVcdFile, zext_ln46_3_fu_160_p1, "zext_ln46_3_fu_160_p1");
    sc_trace(mVcdFile, add_ln46_1_fu_164_p2, "add_ln46_1_fu_164_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

initialize_padded_memory_16_10_0_s::~initialize_padded_memory_16_10_0_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void initialize_padded_memory_16_10_0_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln43_fu_106_p2.read(), ap_const_lv1_1))) {
        m_0_reg_57 = m_reg_187.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        m_0_reg_57 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln45_fu_148_p2.read(), ap_const_lv1_1))) {
        x_0_reg_68 = x_reg_200.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_90_p2.read(), ap_const_lv1_0))) {
        x_0_reg_68 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_0_reg_79 = y_reg_213.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_106_p2.read()))) {
        y_0_reg_79 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_106_p2.read()))) {
        add_ln46_reg_205 = add_ln46_fu_142_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln45_fu_148_p2.read()))) {
        input_addr_reg_218 =  (sc_lv<7>) (zext_ln46_4_fu_169_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        m_reg_187 = m_fu_96_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_reg_200 = x_fu_112_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        y_reg_213 = y_fu_154_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_90_p2.read(), ap_const_lv1_0))) {
        zext_ln46_reg_192 = zext_ln46_fu_102_p1.read();
    }
}

void initialize_padded_memory_16_10_0_s::thread_add_ln46_1_fu_164_p2() {
    add_ln46_1_fu_164_p2 = (!add_ln46_reg_205.read().is_01() || !zext_ln46_3_fu_160_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln46_reg_205.read()) + sc_biguint<8>(zext_ln46_3_fu_160_p1.read()));
}

void initialize_padded_memory_16_10_0_s::thread_add_ln46_fu_142_p2() {
    add_ln46_fu_142_p2 = (!zext_ln46_2_fu_138_p1.read().is_01() || !zext_ln46_1_fu_126_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln46_2_fu_138_p1.read()) + sc_biguint<8>(zext_ln46_1_fu_126_p1.read()));
}

void initialize_padded_memory_16_10_0_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void initialize_padded_memory_16_10_0_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void initialize_padded_memory_16_10_0_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void initialize_padded_memory_16_10_0_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void initialize_padded_memory_16_10_0_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void initialize_padded_memory_16_10_0_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln41_fu_90_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void initialize_padded_memory_16_10_0_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void initialize_padded_memory_16_10_0_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_90_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void initialize_padded_memory_16_10_0_s::thread_icmp_ln41_fu_90_p2() {
    icmp_ln41_fu_90_p2 = (!m_0_reg_57.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_57.read() == ap_const_lv5_10);
}

void initialize_padded_memory_16_10_0_s::thread_icmp_ln43_fu_106_p2() {
    icmp_ln43_fu_106_p2 = (!x_0_reg_68.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_68.read() == ap_const_lv4_A);
}

void initialize_padded_memory_16_10_0_s::thread_icmp_ln45_fu_148_p2() {
    icmp_ln45_fu_148_p2 = (!y_0_reg_79.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_79.read() == ap_const_lv4_A);
}

void initialize_padded_memory_16_10_0_s::thread_input_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_r_address0 = input_addr_reg_218.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        input_r_address0 =  (sc_lv<7>) (zext_ln46_4_fu_169_p1.read());
    } else {
        input_r_address0 = "XXXXXXX";
    }
}

void initialize_padded_memory_16_10_0_s::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void initialize_padded_memory_16_10_0_s::thread_input_r_d0() {
    input_r_d0 = esl_bitset<16,16,6,1>(input_r_q0.read(), zext_ln46_reg_192.read(), ap_const_lv1_0);
}

void initialize_padded_memory_16_10_0_s::thread_input_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_r_we0 = ap_const_logic_1;
    } else {
        input_r_we0 = ap_const_logic_0;
    }
}

void initialize_padded_memory_16_10_0_s::thread_m_fu_96_p2() {
    m_fu_96_p2 = (!m_0_reg_57.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_0_reg_57.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void initialize_padded_memory_16_10_0_s::thread_tmp_16_fu_118_p3() {
    tmp_16_fu_118_p3 = esl_concat<4,3>(x_0_reg_68.read(), ap_const_lv3_0);
}

void initialize_padded_memory_16_10_0_s::thread_tmp_17_fu_130_p3() {
    tmp_17_fu_130_p3 = esl_concat<4,1>(x_0_reg_68.read(), ap_const_lv1_0);
}

void initialize_padded_memory_16_10_0_s::thread_x_fu_112_p2() {
    x_fu_112_p2 = (!x_0_reg_68.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(x_0_reg_68.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void initialize_padded_memory_16_10_0_s::thread_y_fu_154_p2() {
    y_fu_154_p2 = (!y_0_reg_79.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(y_0_reg_79.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void initialize_padded_memory_16_10_0_s::thread_zext_ln46_1_fu_126_p1() {
    zext_ln46_1_fu_126_p1 = esl_zext<8,7>(tmp_16_fu_118_p3.read());
}

void initialize_padded_memory_16_10_0_s::thread_zext_ln46_2_fu_138_p1() {
    zext_ln46_2_fu_138_p1 = esl_zext<8,5>(tmp_17_fu_130_p3.read());
}

void initialize_padded_memory_16_10_0_s::thread_zext_ln46_3_fu_160_p1() {
    zext_ln46_3_fu_160_p1 = esl_zext<8,4>(y_0_reg_79.read());
}

void initialize_padded_memory_16_10_0_s::thread_zext_ln46_4_fu_169_p1() {
    zext_ln46_4_fu_169_p1 = esl_zext<64,8>(add_ln46_1_fu_164_p2.read());
}

void initialize_padded_memory_16_10_0_s::thread_zext_ln46_fu_102_p1() {
    zext_ln46_fu_102_p1 = esl_zext<6,5>(m_0_reg_57.read());
}

void initialize_padded_memory_16_10_0_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_90_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln43_fu_106_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln45_fu_148_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

