// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pool_16_16_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pool_16_16_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pool_16_16_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> max_pool_16_16_s::ap_ST_fsm_state1 = "1";
const sc_lv<4> max_pool_16_16_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<4> max_pool_16_16_s::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<4> max_pool_16_16_s::ap_ST_fsm_state5 = "1000";
const bool max_pool_16_16_s::ap_const_boolean_1 = true;
const sc_lv<32> max_pool_16_16_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pool_16_16_s::ap_const_lv32_1 = "1";
const bool max_pool_16_16_s::ap_const_boolean_0 = false;
const sc_lv<1> max_pool_16_16_s::ap_const_lv1_0 = "0";
const sc_lv<32> max_pool_16_16_s::ap_const_lv32_2 = "10";
const sc_lv<1> max_pool_16_16_s::ap_const_lv1_1 = "1";
const sc_lv<11> max_pool_16_16_s::ap_const_lv11_0 = "00000000000";
const sc_lv<5> max_pool_16_16_s::ap_const_lv5_0 = "00000";
const sc_lv<8> max_pool_16_16_s::ap_const_lv8_0 = "00000000";
const sc_lv<4> max_pool_16_16_s::ap_const_lv4_0 = "0000";
const sc_lv<4> max_pool_16_16_s::ap_const_lv4_1 = "1";
const sc_lv<11> max_pool_16_16_s::ap_const_lv11_400 = "10000000000";
const sc_lv<11> max_pool_16_16_s::ap_const_lv11_1 = "1";
const sc_lv<5> max_pool_16_16_s::ap_const_lv5_1 = "1";
const sc_lv<8> max_pool_16_16_s::ap_const_lv8_40 = "1000000";
const sc_lv<4> max_pool_16_16_s::ap_const_lv4_8 = "1000";
const sc_lv<56> max_pool_16_16_s::ap_const_lv56_0 = "00000000000000000000000000000000000000000000000000000000";
const sc_lv<8> max_pool_16_16_s::ap_const_lv8_1 = "1";
const sc_lv<3> max_pool_16_16_s::ap_const_lv3_0 = "000";
const sc_lv<32> max_pool_16_16_s::ap_const_lv32_3 = "11";

max_pool_16_16_s::max_pool_16_16_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln114_fu_426_p2);
    sensitive << ( zext_ln114_fu_422_p1 );
    sensitive << ( zext_ln110_2_fu_369_p1 );

    SC_METHOD(thread_add_ln97_fu_200_p2);
    sensitive << ( ap_phi_mux_indvar_flatten21_phi_fu_130_p4 );

    SC_METHOD(thread_add_ln99_fu_348_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_153_p4 );

    SC_METHOD(thread_and_ln110_fu_238_p2);
    sensitive << ( icmp_ln101_fu_232_p2 );
    sensitive << ( xor_ln110_fu_226_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln97_fu_194_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten21_phi_fu_130_p4);
    sensitive << ( indvar_flatten21_reg_126 );
    sensitive << ( icmp_ln97_reg_483 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( add_ln97_reg_487 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_153_p4);
    sensitive << ( indvar_flatten_reg_149 );
    sensitive << ( icmp_ln97_reg_483 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln99_reg_597 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_m_0_phi_fu_141_p4);
    sensitive << ( m_0_reg_137 );
    sensitive << ( icmp_ln97_reg_483 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln110_8_reg_555 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_x_0_phi_fu_164_p4);
    sensitive << ( x_0_reg_160 );
    sensitive << ( icmp_ln97_reg_483 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln110_10_reg_567 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_y_0_phi_fu_175_p4);
    sensitive << ( y_0_reg_171 );
    sensitive << ( icmp_ln97_reg_483 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( y_reg_592 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_icmp_ln101_fu_232_p2);
    sensitive << ( icmp_ln97_fu_194_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_y_0_phi_fu_175_p4 );

    SC_METHOD(thread_icmp_ln97_fu_194_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten21_phi_fu_130_p4 );

    SC_METHOD(thread_icmp_ln99_fu_212_p2);
    sensitive << ( icmp_ln97_fu_194_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_153_p4 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_s_fu_302_p5 );
    sensitive << ( tmp_9_fu_373_p5 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_input_r_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_10_fu_337_p4 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_11_fu_392_p4 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_input_r_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_m_fu_206_p2);
    sensitive << ( ap_phi_mux_m_0_phi_fu_141_p4 );

    SC_METHOD(thread_or_ln110_10_fu_270_p2);
    sensitive << ( shl_ln110_3_fu_264_p2 );

    SC_METHOD(thread_or_ln110_5_fu_188_p2);
    sensitive << ( shl_ln110_fu_182_p2 );

    SC_METHOD(thread_or_ln110_6_fu_409_p2);
    sensitive << ( tmp_12_fu_401_p3 );
    sensitive << ( tmp_fu_384_p3 );

    SC_METHOD(thread_or_ln110_7_fu_462_p2);
    sensitive << ( tmp_13_fu_448_p3 );
    sensitive << ( tmp_14_fu_455_p3 );

    SC_METHOD(thread_or_ln110_8_fu_468_p2);
    sensitive << ( or_ln110_6_reg_582 );
    sensitive << ( or_ln110_7_fu_462_p2 );

    SC_METHOD(thread_or_ln110_9_fu_250_p2);
    sensitive << ( icmp_ln99_fu_212_p2 );
    sensitive << ( and_ln110_fu_238_p2 );

    SC_METHOD(thread_or_ln110_fu_331_p2);
    sensitive << ( shl_ln110_4_fu_280_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( output_addr_reg_587 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln114_2_fu_432_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( output_r_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln110_reg_560 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_ln110_8_fu_468_p2 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( icmp_ln97_reg_483 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_select_ln110_10_fu_364_p3);
    sensitive << ( select_ln110_reg_503 );
    sensitive << ( and_ln110_reg_508 );
    sensitive << ( x_reg_513 );

    SC_METHOD(thread_select_ln110_11_fu_286_p3);
    sensitive << ( icmp_ln99_fu_212_p2 );
    sensitive << ( shl_ln110_fu_182_p2 );

    SC_METHOD(thread_select_ln110_12_fu_294_p3);
    sensitive << ( and_ln110_fu_238_p2 );
    sensitive << ( shl_ln110_3_fu_264_p2 );
    sensitive << ( select_ln110_11_fu_286_p3 );

    SC_METHOD(thread_select_ln110_13_fu_315_p3);
    sensitive << ( icmp_ln99_fu_212_p2 );
    sensitive << ( or_ln110_5_fu_188_p2 );

    SC_METHOD(thread_select_ln110_14_fu_323_p3);
    sensitive << ( and_ln110_fu_238_p2 );
    sensitive << ( or_ln110_10_fu_270_p2 );
    sensitive << ( select_ln110_13_fu_315_p3 );

    SC_METHOD(thread_select_ln110_8_fu_354_p3);
    sensitive << ( m_0_reg_137 );
    sensitive << ( m_reg_492 );
    sensitive << ( icmp_ln99_reg_497 );

    SC_METHOD(thread_select_ln110_9_fu_256_p3);
    sensitive << ( ap_phi_mux_y_0_phi_fu_175_p4 );
    sensitive << ( or_ln110_9_fu_250_p2 );

    SC_METHOD(thread_select_ln110_fu_218_p3);
    sensitive << ( icmp_ln99_fu_212_p2 );
    sensitive << ( ap_phi_mux_x_0_phi_fu_164_p4 );

    SC_METHOD(thread_select_ln99_fu_442_p3);
    sensitive << ( icmp_ln99_reg_497 );
    sensitive << ( add_ln99_reg_550 );

    SC_METHOD(thread_shl_ln110_3_fu_264_p2);
    sensitive << ( x_fu_244_p2 );

    SC_METHOD(thread_shl_ln110_4_fu_280_p2);
    sensitive << ( select_ln110_9_fu_256_p3 );

    SC_METHOD(thread_shl_ln110_fu_182_p2);
    sensitive << ( ap_phi_mux_x_0_phi_fu_164_p4 );

    SC_METHOD(thread_tmp_10_fu_337_p4);
    sensitive << ( or_ln110_fu_331_p2 );
    sensitive << ( select_ln110_12_fu_294_p3 );

    SC_METHOD(thread_tmp_11_fu_392_p4);
    sensitive << ( select_ln110_14_reg_534 );
    sensitive << ( or_ln110_reg_540 );

    SC_METHOD(thread_tmp_12_fu_401_p3);
    sensitive << ( input_r_q1 );
    sensitive << ( zext_ln110_fu_360_p1 );

    SC_METHOD(thread_tmp_13_fu_448_p3);
    sensitive << ( input_r_q0 );
    sensitive << ( zext_ln110_reg_560 );

    SC_METHOD(thread_tmp_14_fu_455_p3);
    sensitive << ( input_r_q1 );
    sensitive << ( zext_ln110_reg_560 );

    SC_METHOD(thread_tmp_15_fu_415_p3);
    sensitive << ( select_ln110_9_reg_518 );

    SC_METHOD(thread_tmp_9_fu_373_p5);
    sensitive << ( trunc_ln110_reg_524 );
    sensitive << ( select_ln110_14_reg_534 );

    SC_METHOD(thread_tmp_fu_384_p3);
    sensitive << ( input_r_q0 );
    sensitive << ( zext_ln110_fu_360_p1 );

    SC_METHOD(thread_tmp_s_fu_302_p5);
    sensitive << ( trunc_ln110_fu_276_p1 );
    sensitive << ( select_ln110_12_fu_294_p3 );

    SC_METHOD(thread_trunc_ln110_fu_276_p1);
    sensitive << ( select_ln110_9_fu_256_p3 );

    SC_METHOD(thread_x_fu_244_p2);
    sensitive << ( select_ln110_fu_218_p3 );

    SC_METHOD(thread_xor_ln110_fu_226_p2);
    sensitive << ( icmp_ln99_fu_212_p2 );

    SC_METHOD(thread_y_fu_437_p2);
    sensitive << ( select_ln110_9_reg_518 );

    SC_METHOD(thread_zext_ln110_2_fu_369_p1);
    sensitive << ( select_ln110_10_fu_364_p3 );

    SC_METHOD(thread_zext_ln110_fu_360_p1);
    sensitive << ( select_ln110_8_fu_354_p3 );

    SC_METHOD(thread_zext_ln114_2_fu_432_p1);
    sensitive << ( add_ln114_fu_426_p2 );

    SC_METHOD(thread_zext_ln114_fu_422_p1);
    sensitive << ( tmp_15_fu_415_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln97_fu_194_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pool_16_16_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, input_r_address1, "(port)input_r_address1");
    sc_trace(mVcdFile, input_r_ce1, "(port)input_r_ce1");
    sc_trace(mVcdFile, input_r_q1, "(port)input_r_q1");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten21_reg_126, "indvar_flatten21_reg_126");
    sc_trace(mVcdFile, m_0_reg_137, "m_0_reg_137");
    sc_trace(mVcdFile, indvar_flatten_reg_149, "indvar_flatten_reg_149");
    sc_trace(mVcdFile, x_0_reg_160, "x_0_reg_160");
    sc_trace(mVcdFile, y_0_reg_171, "y_0_reg_171");
    sc_trace(mVcdFile, icmp_ln97_fu_194_p2, "icmp_ln97_fu_194_p2");
    sc_trace(mVcdFile, icmp_ln97_reg_483, "icmp_ln97_reg_483");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln97_fu_200_p2, "add_ln97_fu_200_p2");
    sc_trace(mVcdFile, add_ln97_reg_487, "add_ln97_reg_487");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, m_fu_206_p2, "m_fu_206_p2");
    sc_trace(mVcdFile, m_reg_492, "m_reg_492");
    sc_trace(mVcdFile, icmp_ln99_fu_212_p2, "icmp_ln99_fu_212_p2");
    sc_trace(mVcdFile, icmp_ln99_reg_497, "icmp_ln99_reg_497");
    sc_trace(mVcdFile, select_ln110_fu_218_p3, "select_ln110_fu_218_p3");
    sc_trace(mVcdFile, select_ln110_reg_503, "select_ln110_reg_503");
    sc_trace(mVcdFile, and_ln110_fu_238_p2, "and_ln110_fu_238_p2");
    sc_trace(mVcdFile, and_ln110_reg_508, "and_ln110_reg_508");
    sc_trace(mVcdFile, x_fu_244_p2, "x_fu_244_p2");
    sc_trace(mVcdFile, x_reg_513, "x_reg_513");
    sc_trace(mVcdFile, select_ln110_9_fu_256_p3, "select_ln110_9_fu_256_p3");
    sc_trace(mVcdFile, select_ln110_9_reg_518, "select_ln110_9_reg_518");
    sc_trace(mVcdFile, trunc_ln110_fu_276_p1, "trunc_ln110_fu_276_p1");
    sc_trace(mVcdFile, trunc_ln110_reg_524, "trunc_ln110_reg_524");
    sc_trace(mVcdFile, select_ln110_14_fu_323_p3, "select_ln110_14_fu_323_p3");
    sc_trace(mVcdFile, select_ln110_14_reg_534, "select_ln110_14_reg_534");
    sc_trace(mVcdFile, or_ln110_fu_331_p2, "or_ln110_fu_331_p2");
    sc_trace(mVcdFile, or_ln110_reg_540, "or_ln110_reg_540");
    sc_trace(mVcdFile, add_ln99_fu_348_p2, "add_ln99_fu_348_p2");
    sc_trace(mVcdFile, add_ln99_reg_550, "add_ln99_reg_550");
    sc_trace(mVcdFile, select_ln110_8_fu_354_p3, "select_ln110_8_fu_354_p3");
    sc_trace(mVcdFile, select_ln110_8_reg_555, "select_ln110_8_reg_555");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, zext_ln110_fu_360_p1, "zext_ln110_fu_360_p1");
    sc_trace(mVcdFile, zext_ln110_reg_560, "zext_ln110_reg_560");
    sc_trace(mVcdFile, select_ln110_10_fu_364_p3, "select_ln110_10_fu_364_p3");
    sc_trace(mVcdFile, select_ln110_10_reg_567, "select_ln110_10_reg_567");
    sc_trace(mVcdFile, or_ln110_6_fu_409_p2, "or_ln110_6_fu_409_p2");
    sc_trace(mVcdFile, or_ln110_6_reg_582, "or_ln110_6_reg_582");
    sc_trace(mVcdFile, output_addr_reg_587, "output_addr_reg_587");
    sc_trace(mVcdFile, y_fu_437_p2, "y_fu_437_p2");
    sc_trace(mVcdFile, y_reg_592, "y_reg_592");
    sc_trace(mVcdFile, select_ln99_fu_442_p3, "select_ln99_fu_442_p3");
    sc_trace(mVcdFile, select_ln99_reg_597, "select_ln99_reg_597");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten21_phi_fu_130_p4, "ap_phi_mux_indvar_flatten21_phi_fu_130_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_m_0_phi_fu_141_p4, "ap_phi_mux_m_0_phi_fu_141_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_153_p4, "ap_phi_mux_indvar_flatten_phi_fu_153_p4");
    sc_trace(mVcdFile, ap_phi_mux_x_0_phi_fu_164_p4, "ap_phi_mux_x_0_phi_fu_164_p4");
    sc_trace(mVcdFile, ap_phi_mux_y_0_phi_fu_175_p4, "ap_phi_mux_y_0_phi_fu_175_p4");
    sc_trace(mVcdFile, tmp_s_fu_302_p5, "tmp_s_fu_302_p5");
    sc_trace(mVcdFile, tmp_10_fu_337_p4, "tmp_10_fu_337_p4");
    sc_trace(mVcdFile, tmp_9_fu_373_p5, "tmp_9_fu_373_p5");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, tmp_11_fu_392_p4, "tmp_11_fu_392_p4");
    sc_trace(mVcdFile, zext_ln114_2_fu_432_p1, "zext_ln114_2_fu_432_p1");
    sc_trace(mVcdFile, shl_ln110_fu_182_p2, "shl_ln110_fu_182_p2");
    sc_trace(mVcdFile, icmp_ln101_fu_232_p2, "icmp_ln101_fu_232_p2");
    sc_trace(mVcdFile, xor_ln110_fu_226_p2, "xor_ln110_fu_226_p2");
    sc_trace(mVcdFile, or_ln110_9_fu_250_p2, "or_ln110_9_fu_250_p2");
    sc_trace(mVcdFile, shl_ln110_3_fu_264_p2, "shl_ln110_3_fu_264_p2");
    sc_trace(mVcdFile, select_ln110_11_fu_286_p3, "select_ln110_11_fu_286_p3");
    sc_trace(mVcdFile, select_ln110_12_fu_294_p3, "select_ln110_12_fu_294_p3");
    sc_trace(mVcdFile, or_ln110_5_fu_188_p2, "or_ln110_5_fu_188_p2");
    sc_trace(mVcdFile, or_ln110_10_fu_270_p2, "or_ln110_10_fu_270_p2");
    sc_trace(mVcdFile, select_ln110_13_fu_315_p3, "select_ln110_13_fu_315_p3");
    sc_trace(mVcdFile, shl_ln110_4_fu_280_p2, "shl_ln110_4_fu_280_p2");
    sc_trace(mVcdFile, tmp_12_fu_401_p3, "tmp_12_fu_401_p3");
    sc_trace(mVcdFile, tmp_fu_384_p3, "tmp_fu_384_p3");
    sc_trace(mVcdFile, tmp_15_fu_415_p3, "tmp_15_fu_415_p3");
    sc_trace(mVcdFile, zext_ln114_fu_422_p1, "zext_ln114_fu_422_p1");
    sc_trace(mVcdFile, zext_ln110_2_fu_369_p1, "zext_ln110_2_fu_369_p1");
    sc_trace(mVcdFile, add_ln114_fu_426_p2, "add_ln114_fu_426_p2");
    sc_trace(mVcdFile, tmp_13_fu_448_p3, "tmp_13_fu_448_p3");
    sc_trace(mVcdFile, tmp_14_fu_455_p3, "tmp_14_fu_455_p3");
    sc_trace(mVcdFile, or_ln110_7_fu_462_p2, "or_ln110_7_fu_462_p2");
    sc_trace(mVcdFile, or_ln110_8_fu_468_p2, "or_ln110_8_fu_468_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

max_pool_16_16_s::~max_pool_16_16_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void max_pool_16_16_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten21_reg_126 = add_ln97_reg_487.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten21_reg_126 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_149 = select_ln99_reg_597.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_149 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        m_0_reg_137 = select_ln110_8_reg_555.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        m_0_reg_137 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        x_0_reg_160 = select_ln110_10_reg_567.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_0_reg_160 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        y_0_reg_171 = y_reg_592.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        y_0_reg_171 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        add_ln97_reg_487 = add_ln97_fu_200_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_fu_194_p2.read(), ap_const_lv1_0))) {
        add_ln99_reg_550 = add_ln99_fu_348_p2.read();
        and_ln110_reg_508 = and_ln110_fu_238_p2.read();
        icmp_ln99_reg_497 = icmp_ln99_fu_212_p2.read();
        m_reg_492 = m_fu_206_p2.read();
        or_ln110_reg_540 = or_ln110_fu_331_p2.read();
        select_ln110_14_reg_534 = select_ln110_14_fu_323_p3.read();
        select_ln110_9_reg_518 = select_ln110_9_fu_256_p3.read();
        select_ln110_reg_503 = select_ln110_fu_218_p3.read();
        trunc_ln110_reg_524 = trunc_ln110_fu_276_p1.read();
        x_reg_513 = x_fu_244_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln97_reg_483 = icmp_ln97_fu_194_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0))) {
        or_ln110_6_reg_582 = or_ln110_6_fu_409_p2.read();
        output_addr_reg_587 =  (sc_lv<6>) (zext_ln114_2_fu_432_p1.read());
        zext_ln110_reg_560 = zext_ln110_fu_360_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0))) {
        select_ln110_10_reg_567 = select_ln110_10_fu_364_p3.read();
        select_ln110_8_reg_555 = select_ln110_8_fu_354_p3.read();
        select_ln99_reg_597 = select_ln99_fu_442_p3.read();
        y_reg_592 = y_fu_437_p2.read();
    }
}

void max_pool_16_16_s::thread_add_ln114_fu_426_p2() {
    add_ln114_fu_426_p2 = (!zext_ln114_fu_422_p1.read().is_01() || !zext_ln110_2_fu_369_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln114_fu_422_p1.read()) + sc_biguint<8>(zext_ln110_2_fu_369_p1.read()));
}

void max_pool_16_16_s::thread_add_ln97_fu_200_p2() {
    add_ln97_fu_200_p2 = (!ap_const_lv11_1.is_01() || !ap_phi_mux_indvar_flatten21_phi_fu_130_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_1) + sc_biguint<11>(ap_phi_mux_indvar_flatten21_phi_fu_130_p4.read()));
}

void max_pool_16_16_s::thread_add_ln99_fu_348_p2() {
    add_ln99_fu_348_p2 = (!ap_const_lv8_1.is_01() || !ap_phi_mux_indvar_flatten_phi_fu_153_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(ap_phi_mux_indvar_flatten_phi_fu_153_p4.read()));
}

void max_pool_16_16_s::thread_and_ln110_fu_238_p2() {
    and_ln110_fu_238_p2 = (icmp_ln101_fu_232_p2.read() & xor_ln110_fu_226_p2.read());
}

void max_pool_16_16_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void max_pool_16_16_s::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void max_pool_16_16_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pool_16_16_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void max_pool_16_16_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_16_16_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln97_fu_194_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void max_pool_16_16_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_ap_phi_mux_indvar_flatten21_phi_fu_130_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten21_phi_fu_130_p4 = add_ln97_reg_487.read();
    } else {
        ap_phi_mux_indvar_flatten21_phi_fu_130_p4 = indvar_flatten21_reg_126.read();
    }
}

void max_pool_16_16_s::thread_ap_phi_mux_indvar_flatten_phi_fu_153_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_153_p4 = select_ln99_reg_597.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_153_p4 = indvar_flatten_reg_149.read();
    }
}

void max_pool_16_16_s::thread_ap_phi_mux_m_0_phi_fu_141_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_m_0_phi_fu_141_p4 = select_ln110_8_reg_555.read();
    } else {
        ap_phi_mux_m_0_phi_fu_141_p4 = m_0_reg_137.read();
    }
}

void max_pool_16_16_s::thread_ap_phi_mux_x_0_phi_fu_164_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_x_0_phi_fu_164_p4 = select_ln110_10_reg_567.read();
    } else {
        ap_phi_mux_x_0_phi_fu_164_p4 = x_0_reg_160.read();
    }
}

void max_pool_16_16_s::thread_ap_phi_mux_y_0_phi_fu_175_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_y_0_phi_fu_175_p4 = y_reg_592.read();
    } else {
        ap_phi_mux_y_0_phi_fu_175_p4 = y_0_reg_171.read();
    }
}

void max_pool_16_16_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_icmp_ln101_fu_232_p2() {
    icmp_ln101_fu_232_p2 = (!ap_phi_mux_y_0_phi_fu_175_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_y_0_phi_fu_175_p4.read() == ap_const_lv4_8);
}

void max_pool_16_16_s::thread_icmp_ln97_fu_194_p2() {
    icmp_ln97_fu_194_p2 = (!ap_phi_mux_indvar_flatten21_phi_fu_130_p4.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten21_phi_fu_130_p4.read() == ap_const_lv11_400);
}

void max_pool_16_16_s::thread_icmp_ln99_fu_212_p2() {
    icmp_ln99_fu_212_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_153_p4.read().is_01() || !ap_const_lv8_40.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_153_p4.read() == ap_const_lv8_40);
}

void max_pool_16_16_s::thread_input_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            input_r_address0 =  (sc_lv<8>) (tmp_9_fu_373_p5.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            input_r_address0 =  (sc_lv<8>) (tmp_s_fu_302_p5.read());
        } else {
            input_r_address0 = "XXXXXXXX";
        }
    } else {
        input_r_address0 = "XXXXXXXX";
    }
}

void max_pool_16_16_s::thread_input_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<8>) (tmp_11_fu_392_p4.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<8>) (tmp_10_fu_337_p4.read());
        } else {
            input_r_address1 = "XXXXXXXX";
        }
    } else {
        input_r_address1 = "XXXXXXXX";
    }
}

void max_pool_16_16_s::thread_input_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_input_r_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        input_r_ce1 = ap_const_logic_1;
    } else {
        input_r_ce1 = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_m_fu_206_p2() {
    m_fu_206_p2 = (!ap_const_lv5_1.is_01() || !ap_phi_mux_m_0_phi_fu_141_p4.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(ap_phi_mux_m_0_phi_fu_141_p4.read()));
}

void max_pool_16_16_s::thread_or_ln110_10_fu_270_p2() {
    or_ln110_10_fu_270_p2 = (shl_ln110_3_fu_264_p2.read() | ap_const_lv4_1);
}

void max_pool_16_16_s::thread_or_ln110_5_fu_188_p2() {
    or_ln110_5_fu_188_p2 = (shl_ln110_fu_182_p2.read() | ap_const_lv4_1);
}

void max_pool_16_16_s::thread_or_ln110_6_fu_409_p2() {
    or_ln110_6_fu_409_p2 = (tmp_12_fu_401_p3.read() | tmp_fu_384_p3.read());
}

void max_pool_16_16_s::thread_or_ln110_7_fu_462_p2() {
    or_ln110_7_fu_462_p2 = (tmp_13_fu_448_p3.read() | tmp_14_fu_455_p3.read());
}

void max_pool_16_16_s::thread_or_ln110_8_fu_468_p2() {
    or_ln110_8_fu_468_p2 = (or_ln110_7_fu_462_p2.read() | or_ln110_6_reg_582.read());
}

void max_pool_16_16_s::thread_or_ln110_9_fu_250_p2() {
    or_ln110_9_fu_250_p2 = (and_ln110_fu_238_p2.read() | icmp_ln99_fu_212_p2.read());
}

void max_pool_16_16_s::thread_or_ln110_fu_331_p2() {
    or_ln110_fu_331_p2 = (shl_ln110_4_fu_280_p2.read() | ap_const_lv4_1);
}

void max_pool_16_16_s::thread_output_r_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        output_r_address0 = output_addr_reg_587.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        output_r_address0 =  (sc_lv<6>) (zext_ln114_2_fu_432_p1.read());
    } else {
        output_r_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void max_pool_16_16_s::thread_output_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_output_r_d0() {
    output_r_d0 = esl_bitset<16,16,6,1>(output_r_q0.read(), zext_ln110_reg_560.read(), or_ln110_8_fu_468_p2.read());
}

void max_pool_16_16_s::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_483.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void max_pool_16_16_s::thread_select_ln110_10_fu_364_p3() {
    select_ln110_10_fu_364_p3 = (!and_ln110_reg_508.read()[0].is_01())? sc_lv<4>(): ((and_ln110_reg_508.read()[0].to_bool())? x_reg_513.read(): select_ln110_reg_503.read());
}

void max_pool_16_16_s::thread_select_ln110_11_fu_286_p3() {
    select_ln110_11_fu_286_p3 = (!icmp_ln99_fu_212_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln99_fu_212_p2.read()[0].to_bool())? ap_const_lv4_0: shl_ln110_fu_182_p2.read());
}

void max_pool_16_16_s::thread_select_ln110_12_fu_294_p3() {
    select_ln110_12_fu_294_p3 = (!and_ln110_fu_238_p2.read()[0].is_01())? sc_lv<4>(): ((and_ln110_fu_238_p2.read()[0].to_bool())? shl_ln110_3_fu_264_p2.read(): select_ln110_11_fu_286_p3.read());
}

void max_pool_16_16_s::thread_select_ln110_13_fu_315_p3() {
    select_ln110_13_fu_315_p3 = (!icmp_ln99_fu_212_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln99_fu_212_p2.read()[0].to_bool())? ap_const_lv4_1: or_ln110_5_fu_188_p2.read());
}

void max_pool_16_16_s::thread_select_ln110_14_fu_323_p3() {
    select_ln110_14_fu_323_p3 = (!and_ln110_fu_238_p2.read()[0].is_01())? sc_lv<4>(): ((and_ln110_fu_238_p2.read()[0].to_bool())? or_ln110_10_fu_270_p2.read(): select_ln110_13_fu_315_p3.read());
}

void max_pool_16_16_s::thread_select_ln110_8_fu_354_p3() {
    select_ln110_8_fu_354_p3 = (!icmp_ln99_reg_497.read()[0].is_01())? sc_lv<5>(): ((icmp_ln99_reg_497.read()[0].to_bool())? m_reg_492.read(): m_0_reg_137.read());
}

void max_pool_16_16_s::thread_select_ln110_9_fu_256_p3() {
    select_ln110_9_fu_256_p3 = (!or_ln110_9_fu_250_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln110_9_fu_250_p2.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_y_0_phi_fu_175_p4.read());
}

void max_pool_16_16_s::thread_select_ln110_fu_218_p3() {
    select_ln110_fu_218_p3 = (!icmp_ln99_fu_212_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln99_fu_212_p2.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_x_0_phi_fu_164_p4.read());
}

void max_pool_16_16_s::thread_select_ln99_fu_442_p3() {
    select_ln99_fu_442_p3 = (!icmp_ln99_reg_497.read()[0].is_01())? sc_lv<8>(): ((icmp_ln99_reg_497.read()[0].to_bool())? ap_const_lv8_1: add_ln99_reg_550.read());
}

void max_pool_16_16_s::thread_shl_ln110_3_fu_264_p2() {
    shl_ln110_3_fu_264_p2 = (!ap_const_lv4_1.is_01())? sc_lv<4>(): x_fu_244_p2.read() << (unsigned short)ap_const_lv4_1.to_uint();
}

void max_pool_16_16_s::thread_shl_ln110_4_fu_280_p2() {
    shl_ln110_4_fu_280_p2 = (!ap_const_lv4_1.is_01())? sc_lv<4>(): select_ln110_9_fu_256_p3.read() << (unsigned short)ap_const_lv4_1.to_uint();
}

void max_pool_16_16_s::thread_shl_ln110_fu_182_p2() {
    shl_ln110_fu_182_p2 = (!ap_const_lv4_1.is_01())? sc_lv<4>(): ap_phi_mux_x_0_phi_fu_164_p4.read() << (unsigned short)ap_const_lv4_1.to_uint();
}

void max_pool_16_16_s::thread_tmp_10_fu_337_p4() {
    tmp_10_fu_337_p4 = esl_concat<60,4>(esl_concat<56,4>(ap_const_lv56_0, or_ln110_fu_331_p2.read()), select_ln110_12_fu_294_p3.read());
}

void max_pool_16_16_s::thread_tmp_11_fu_392_p4() {
    tmp_11_fu_392_p4 = esl_concat<60,4>(esl_concat<56,4>(ap_const_lv56_0, or_ln110_reg_540.read()), select_ln110_14_reg_534.read());
}

void max_pool_16_16_s::thread_tmp_12_fu_401_p3() {
    tmp_12_fu_401_p3 = (!zext_ln110_fu_360_p1.read().is_01() || sc_biguint<6>(zext_ln110_fu_360_p1.read()).to_uint() >= 16)? sc_lv<1>(): input_r_q1.read().range(sc_biguint<6>(zext_ln110_fu_360_p1.read()).to_uint(), sc_biguint<6>(zext_ln110_fu_360_p1.read()).to_uint());
}

void max_pool_16_16_s::thread_tmp_13_fu_448_p3() {
    tmp_13_fu_448_p3 = (!zext_ln110_reg_560.read().is_01() || sc_biguint<6>(zext_ln110_reg_560.read()).to_uint() >= 16)? sc_lv<1>(): input_r_q0.read().range(sc_biguint<6>(zext_ln110_reg_560.read()).to_uint(), sc_biguint<6>(zext_ln110_reg_560.read()).to_uint());
}

void max_pool_16_16_s::thread_tmp_14_fu_455_p3() {
    tmp_14_fu_455_p3 = (!zext_ln110_reg_560.read().is_01() || sc_biguint<6>(zext_ln110_reg_560.read()).to_uint() >= 16)? sc_lv<1>(): input_r_q1.read().range(sc_biguint<6>(zext_ln110_reg_560.read()).to_uint(), sc_biguint<6>(zext_ln110_reg_560.read()).to_uint());
}

void max_pool_16_16_s::thread_tmp_15_fu_415_p3() {
    tmp_15_fu_415_p3 = esl_concat<4,3>(select_ln110_9_reg_518.read(), ap_const_lv3_0);
}

void max_pool_16_16_s::thread_tmp_9_fu_373_p5() {
    tmp_9_fu_373_p5 = esl_concat<60,4>(esl_concat<59,1>(esl_concat<56,3>(ap_const_lv56_0, trunc_ln110_reg_524.read()), ap_const_lv1_0), select_ln110_14_reg_534.read());
}

void max_pool_16_16_s::thread_tmp_fu_384_p3() {
    tmp_fu_384_p3 = (!zext_ln110_fu_360_p1.read().is_01() || sc_biguint<6>(zext_ln110_fu_360_p1.read()).to_uint() >= 16)? sc_lv<1>(): input_r_q0.read().range(sc_biguint<6>(zext_ln110_fu_360_p1.read()).to_uint(), sc_biguint<6>(zext_ln110_fu_360_p1.read()).to_uint());
}

void max_pool_16_16_s::thread_tmp_s_fu_302_p5() {
    tmp_s_fu_302_p5 = esl_concat<60,4>(esl_concat<59,1>(esl_concat<56,3>(ap_const_lv56_0, trunc_ln110_fu_276_p1.read()), ap_const_lv1_0), select_ln110_12_fu_294_p3.read());
}

void max_pool_16_16_s::thread_trunc_ln110_fu_276_p1() {
    trunc_ln110_fu_276_p1 = select_ln110_9_fu_256_p3.read().range(3-1, 0);
}

void max_pool_16_16_s::thread_x_fu_244_p2() {
    x_fu_244_p2 = (!ap_const_lv4_1.is_01() || !select_ln110_fu_218_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(select_ln110_fu_218_p3.read()));
}

void max_pool_16_16_s::thread_xor_ln110_fu_226_p2() {
    xor_ln110_fu_226_p2 = (icmp_ln99_fu_212_p2.read() ^ ap_const_lv1_1);
}

void max_pool_16_16_s::thread_y_fu_437_p2() {
    y_fu_437_p2 = (!ap_const_lv4_1.is_01() || !select_ln110_9_reg_518.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(select_ln110_9_reg_518.read()));
}

void max_pool_16_16_s::thread_zext_ln110_2_fu_369_p1() {
    zext_ln110_2_fu_369_p1 = esl_zext<8,4>(select_ln110_10_fu_364_p3.read());
}

void max_pool_16_16_s::thread_zext_ln110_fu_360_p1() {
    zext_ln110_fu_360_p1 = esl_zext<6,5>(select_ln110_8_fu_354_p3.read());
}

void max_pool_16_16_s::thread_zext_ln114_2_fu_432_p1() {
    zext_ln114_2_fu_432_p1 = esl_zext<64,8>(add_ln114_fu_426_p2.read());
}

void max_pool_16_16_s::thread_zext_ln114_fu_422_p1() {
    zext_ln114_fu_422_p1 = esl_zext<8,7>(tmp_15_fu_415_p3.read());
}

void max_pool_16_16_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_fu_194_p2.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_fu_194_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

