// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pool_32_8_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pool_32_8_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pool_32_8_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> max_pool_32_8_s::ap_ST_fsm_state1 = "1";
const sc_lv<4> max_pool_32_8_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<4> max_pool_32_8_s::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<4> max_pool_32_8_s::ap_ST_fsm_state5 = "1000";
const bool max_pool_32_8_s::ap_const_boolean_1 = true;
const sc_lv<32> max_pool_32_8_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pool_32_8_s::ap_const_lv32_1 = "1";
const bool max_pool_32_8_s::ap_const_boolean_0 = false;
const sc_lv<1> max_pool_32_8_s::ap_const_lv1_0 = "0";
const sc_lv<32> max_pool_32_8_s::ap_const_lv32_2 = "10";
const sc_lv<1> max_pool_32_8_s::ap_const_lv1_1 = "1";
const sc_lv<10> max_pool_32_8_s::ap_const_lv10_0 = "0000000000";
const sc_lv<6> max_pool_32_8_s::ap_const_lv6_0 = "000000";
const sc_lv<3> max_pool_32_8_s::ap_const_lv3_0 = "000";
const sc_lv<3> max_pool_32_8_s::ap_const_lv3_1 = "1";
const sc_lv<10> max_pool_32_8_s::ap_const_lv10_200 = "1000000000";
const sc_lv<10> max_pool_32_8_s::ap_const_lv10_1 = "1";
const sc_lv<6> max_pool_32_8_s::ap_const_lv6_1 = "1";
const sc_lv<6> max_pool_32_8_s::ap_const_lv6_10 = "10000";
const sc_lv<3> max_pool_32_8_s::ap_const_lv3_4 = "100";
const sc_lv<58> max_pool_32_8_s::ap_const_lv58_0 = "0000000000000000000000000000000000000000000000000000000000";
const sc_lv<2> max_pool_32_8_s::ap_const_lv2_0 = "00";
const sc_lv<32> max_pool_32_8_s::ap_const_lv32_3 = "11";

max_pool_32_8_s::max_pool_32_8_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln114_fu_422_p2);
    sensitive << ( zext_ln114_fu_418_p1 );
    sensitive << ( zext_ln110_1_fu_365_p1 );

    SC_METHOD(thread_add_ln97_fu_196_p2);
    sensitive << ( ap_phi_mux_indvar_flatten21_phi_fu_126_p4 );

    SC_METHOD(thread_add_ln99_fu_344_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_149_p4 );

    SC_METHOD(thread_and_ln110_fu_234_p2);
    sensitive << ( icmp_ln101_fu_228_p2 );
    sensitive << ( xor_ln110_fu_222_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln97_fu_190_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten21_phi_fu_126_p4);
    sensitive << ( indvar_flatten21_reg_122 );
    sensitive << ( icmp_ln97_reg_479 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( add_ln97_reg_483 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_149_p4);
    sensitive << ( indvar_flatten_reg_145 );
    sensitive << ( icmp_ln97_reg_479 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln99_reg_593 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_m_0_phi_fu_137_p4);
    sensitive << ( m_0_reg_133 );
    sensitive << ( icmp_ln97_reg_479 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln110_1_reg_551 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_x_0_phi_fu_160_p4);
    sensitive << ( x_0_reg_156 );
    sensitive << ( icmp_ln97_reg_479 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln110_3_reg_563 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_y_0_phi_fu_171_p4);
    sensitive << ( y_0_reg_167 );
    sensitive << ( icmp_ln97_reg_479 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( y_reg_588 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_icmp_ln101_fu_228_p2);
    sensitive << ( icmp_ln97_fu_190_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_y_0_phi_fu_171_p4 );

    SC_METHOD(thread_icmp_ln97_fu_190_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten21_phi_fu_126_p4 );

    SC_METHOD(thread_icmp_ln99_fu_208_p2);
    sensitive << ( icmp_ln97_fu_190_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_149_p4 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_s_fu_298_p5 );
    sensitive << ( tmp_1_fu_369_p5 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_input_r_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_fu_333_p4 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_3_fu_388_p4 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_input_r_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_m_fu_202_p2);
    sensitive << ( ap_phi_mux_m_0_phi_fu_137_p4 );

    SC_METHOD(thread_or_ln110_1_fu_184_p2);
    sensitive << ( shl_ln110_fu_178_p2 );

    SC_METHOD(thread_or_ln110_2_fu_405_p2);
    sensitive << ( tmp_4_fu_397_p3 );
    sensitive << ( tmp_fu_380_p3 );

    SC_METHOD(thread_or_ln110_3_fu_458_p2);
    sensitive << ( tmp_5_fu_444_p3 );
    sensitive << ( tmp_6_fu_451_p3 );

    SC_METHOD(thread_or_ln110_4_fu_464_p2);
    sensitive << ( or_ln110_2_reg_578 );
    sensitive << ( or_ln110_3_fu_458_p2 );

    SC_METHOD(thread_or_ln110_5_fu_246_p2);
    sensitive << ( icmp_ln99_fu_208_p2 );
    sensitive << ( and_ln110_fu_234_p2 );

    SC_METHOD(thread_or_ln110_6_fu_266_p2);
    sensitive << ( shl_ln110_1_fu_260_p2 );

    SC_METHOD(thread_or_ln110_fu_327_p2);
    sensitive << ( shl_ln110_2_fu_276_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( output_addr_reg_583 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln114_1_fu_428_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( output_r_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln110_reg_556 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_ln110_4_fu_464_p2 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( icmp_ln97_reg_479 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_select_ln110_1_fu_350_p3);
    sensitive << ( m_0_reg_133 );
    sensitive << ( m_reg_488 );
    sensitive << ( icmp_ln99_reg_493 );

    SC_METHOD(thread_select_ln110_2_fu_252_p3);
    sensitive << ( ap_phi_mux_y_0_phi_fu_171_p4 );
    sensitive << ( or_ln110_5_fu_246_p2 );

    SC_METHOD(thread_select_ln110_3_fu_360_p3);
    sensitive << ( select_ln110_reg_499 );
    sensitive << ( and_ln110_reg_504 );
    sensitive << ( x_reg_509 );

    SC_METHOD(thread_select_ln110_4_fu_282_p3);
    sensitive << ( icmp_ln99_fu_208_p2 );
    sensitive << ( shl_ln110_fu_178_p2 );

    SC_METHOD(thread_select_ln110_5_fu_290_p3);
    sensitive << ( and_ln110_fu_234_p2 );
    sensitive << ( shl_ln110_1_fu_260_p2 );
    sensitive << ( select_ln110_4_fu_282_p3 );

    SC_METHOD(thread_select_ln110_6_fu_311_p3);
    sensitive << ( icmp_ln99_fu_208_p2 );
    sensitive << ( or_ln110_1_fu_184_p2 );

    SC_METHOD(thread_select_ln110_7_fu_319_p3);
    sensitive << ( and_ln110_fu_234_p2 );
    sensitive << ( or_ln110_6_fu_266_p2 );
    sensitive << ( select_ln110_6_fu_311_p3 );

    SC_METHOD(thread_select_ln110_fu_214_p3);
    sensitive << ( icmp_ln99_fu_208_p2 );
    sensitive << ( ap_phi_mux_x_0_phi_fu_160_p4 );

    SC_METHOD(thread_select_ln99_fu_438_p3);
    sensitive << ( icmp_ln99_reg_493 );
    sensitive << ( add_ln99_reg_546 );

    SC_METHOD(thread_shl_ln110_1_fu_260_p2);
    sensitive << ( x_fu_240_p2 );

    SC_METHOD(thread_shl_ln110_2_fu_276_p2);
    sensitive << ( select_ln110_2_fu_252_p3 );

    SC_METHOD(thread_shl_ln110_fu_178_p2);
    sensitive << ( ap_phi_mux_x_0_phi_fu_160_p4 );

    SC_METHOD(thread_tmp_1_fu_369_p5);
    sensitive << ( trunc_ln110_reg_520 );
    sensitive << ( select_ln110_7_reg_530 );

    SC_METHOD(thread_tmp_2_fu_333_p4);
    sensitive << ( or_ln110_fu_327_p2 );
    sensitive << ( select_ln110_5_fu_290_p3 );

    SC_METHOD(thread_tmp_3_fu_388_p4);
    sensitive << ( select_ln110_7_reg_530 );
    sensitive << ( or_ln110_reg_536 );

    SC_METHOD(thread_tmp_4_fu_397_p3);
    sensitive << ( input_r_q1 );
    sensitive << ( zext_ln110_fu_356_p1 );

    SC_METHOD(thread_tmp_5_fu_444_p3);
    sensitive << ( input_r_q0 );
    sensitive << ( zext_ln110_reg_556 );

    SC_METHOD(thread_tmp_6_fu_451_p3);
    sensitive << ( input_r_q1 );
    sensitive << ( zext_ln110_reg_556 );

    SC_METHOD(thread_tmp_8_fu_411_p3);
    sensitive << ( select_ln110_2_reg_514 );

    SC_METHOD(thread_tmp_fu_380_p3);
    sensitive << ( input_r_q0 );
    sensitive << ( zext_ln110_fu_356_p1 );

    SC_METHOD(thread_tmp_s_fu_298_p5);
    sensitive << ( trunc_ln110_fu_272_p1 );
    sensitive << ( select_ln110_5_fu_290_p3 );

    SC_METHOD(thread_trunc_ln110_fu_272_p1);
    sensitive << ( select_ln110_2_fu_252_p3 );

    SC_METHOD(thread_x_fu_240_p2);
    sensitive << ( select_ln110_fu_214_p3 );

    SC_METHOD(thread_xor_ln110_fu_222_p2);
    sensitive << ( icmp_ln99_fu_208_p2 );

    SC_METHOD(thread_y_fu_433_p2);
    sensitive << ( select_ln110_2_reg_514 );

    SC_METHOD(thread_zext_ln110_1_fu_365_p1);
    sensitive << ( select_ln110_3_fu_360_p3 );

    SC_METHOD(thread_zext_ln110_fu_356_p1);
    sensitive << ( select_ln110_1_fu_350_p3 );

    SC_METHOD(thread_zext_ln114_1_fu_428_p1);
    sensitive << ( add_ln114_fu_422_p2 );

    SC_METHOD(thread_zext_ln114_fu_418_p1);
    sensitive << ( tmp_8_fu_411_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln97_fu_190_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pool_32_8_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, input_r_address1, "(port)input_r_address1");
    sc_trace(mVcdFile, input_r_ce1, "(port)input_r_ce1");
    sc_trace(mVcdFile, input_r_q1, "(port)input_r_q1");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten21_reg_122, "indvar_flatten21_reg_122");
    sc_trace(mVcdFile, m_0_reg_133, "m_0_reg_133");
    sc_trace(mVcdFile, indvar_flatten_reg_145, "indvar_flatten_reg_145");
    sc_trace(mVcdFile, x_0_reg_156, "x_0_reg_156");
    sc_trace(mVcdFile, y_0_reg_167, "y_0_reg_167");
    sc_trace(mVcdFile, icmp_ln97_fu_190_p2, "icmp_ln97_fu_190_p2");
    sc_trace(mVcdFile, icmp_ln97_reg_479, "icmp_ln97_reg_479");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln97_fu_196_p2, "add_ln97_fu_196_p2");
    sc_trace(mVcdFile, add_ln97_reg_483, "add_ln97_reg_483");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, m_fu_202_p2, "m_fu_202_p2");
    sc_trace(mVcdFile, m_reg_488, "m_reg_488");
    sc_trace(mVcdFile, icmp_ln99_fu_208_p2, "icmp_ln99_fu_208_p2");
    sc_trace(mVcdFile, icmp_ln99_reg_493, "icmp_ln99_reg_493");
    sc_trace(mVcdFile, select_ln110_fu_214_p3, "select_ln110_fu_214_p3");
    sc_trace(mVcdFile, select_ln110_reg_499, "select_ln110_reg_499");
    sc_trace(mVcdFile, and_ln110_fu_234_p2, "and_ln110_fu_234_p2");
    sc_trace(mVcdFile, and_ln110_reg_504, "and_ln110_reg_504");
    sc_trace(mVcdFile, x_fu_240_p2, "x_fu_240_p2");
    sc_trace(mVcdFile, x_reg_509, "x_reg_509");
    sc_trace(mVcdFile, select_ln110_2_fu_252_p3, "select_ln110_2_fu_252_p3");
    sc_trace(mVcdFile, select_ln110_2_reg_514, "select_ln110_2_reg_514");
    sc_trace(mVcdFile, trunc_ln110_fu_272_p1, "trunc_ln110_fu_272_p1");
    sc_trace(mVcdFile, trunc_ln110_reg_520, "trunc_ln110_reg_520");
    sc_trace(mVcdFile, select_ln110_7_fu_319_p3, "select_ln110_7_fu_319_p3");
    sc_trace(mVcdFile, select_ln110_7_reg_530, "select_ln110_7_reg_530");
    sc_trace(mVcdFile, or_ln110_fu_327_p2, "or_ln110_fu_327_p2");
    sc_trace(mVcdFile, or_ln110_reg_536, "or_ln110_reg_536");
    sc_trace(mVcdFile, add_ln99_fu_344_p2, "add_ln99_fu_344_p2");
    sc_trace(mVcdFile, add_ln99_reg_546, "add_ln99_reg_546");
    sc_trace(mVcdFile, select_ln110_1_fu_350_p3, "select_ln110_1_fu_350_p3");
    sc_trace(mVcdFile, select_ln110_1_reg_551, "select_ln110_1_reg_551");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, zext_ln110_fu_356_p1, "zext_ln110_fu_356_p1");
    sc_trace(mVcdFile, zext_ln110_reg_556, "zext_ln110_reg_556");
    sc_trace(mVcdFile, select_ln110_3_fu_360_p3, "select_ln110_3_fu_360_p3");
    sc_trace(mVcdFile, select_ln110_3_reg_563, "select_ln110_3_reg_563");
    sc_trace(mVcdFile, or_ln110_2_fu_405_p2, "or_ln110_2_fu_405_p2");
    sc_trace(mVcdFile, or_ln110_2_reg_578, "or_ln110_2_reg_578");
    sc_trace(mVcdFile, output_addr_reg_583, "output_addr_reg_583");
    sc_trace(mVcdFile, y_fu_433_p2, "y_fu_433_p2");
    sc_trace(mVcdFile, y_reg_588, "y_reg_588");
    sc_trace(mVcdFile, select_ln99_fu_438_p3, "select_ln99_fu_438_p3");
    sc_trace(mVcdFile, select_ln99_reg_593, "select_ln99_reg_593");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten21_phi_fu_126_p4, "ap_phi_mux_indvar_flatten21_phi_fu_126_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_m_0_phi_fu_137_p4, "ap_phi_mux_m_0_phi_fu_137_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_149_p4, "ap_phi_mux_indvar_flatten_phi_fu_149_p4");
    sc_trace(mVcdFile, ap_phi_mux_x_0_phi_fu_160_p4, "ap_phi_mux_x_0_phi_fu_160_p4");
    sc_trace(mVcdFile, ap_phi_mux_y_0_phi_fu_171_p4, "ap_phi_mux_y_0_phi_fu_171_p4");
    sc_trace(mVcdFile, tmp_s_fu_298_p5, "tmp_s_fu_298_p5");
    sc_trace(mVcdFile, tmp_2_fu_333_p4, "tmp_2_fu_333_p4");
    sc_trace(mVcdFile, tmp_1_fu_369_p5, "tmp_1_fu_369_p5");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, tmp_3_fu_388_p4, "tmp_3_fu_388_p4");
    sc_trace(mVcdFile, zext_ln114_1_fu_428_p1, "zext_ln114_1_fu_428_p1");
    sc_trace(mVcdFile, shl_ln110_fu_178_p2, "shl_ln110_fu_178_p2");
    sc_trace(mVcdFile, icmp_ln101_fu_228_p2, "icmp_ln101_fu_228_p2");
    sc_trace(mVcdFile, xor_ln110_fu_222_p2, "xor_ln110_fu_222_p2");
    sc_trace(mVcdFile, or_ln110_5_fu_246_p2, "or_ln110_5_fu_246_p2");
    sc_trace(mVcdFile, shl_ln110_1_fu_260_p2, "shl_ln110_1_fu_260_p2");
    sc_trace(mVcdFile, select_ln110_4_fu_282_p3, "select_ln110_4_fu_282_p3");
    sc_trace(mVcdFile, select_ln110_5_fu_290_p3, "select_ln110_5_fu_290_p3");
    sc_trace(mVcdFile, or_ln110_1_fu_184_p2, "or_ln110_1_fu_184_p2");
    sc_trace(mVcdFile, or_ln110_6_fu_266_p2, "or_ln110_6_fu_266_p2");
    sc_trace(mVcdFile, select_ln110_6_fu_311_p3, "select_ln110_6_fu_311_p3");
    sc_trace(mVcdFile, shl_ln110_2_fu_276_p2, "shl_ln110_2_fu_276_p2");
    sc_trace(mVcdFile, tmp_4_fu_397_p3, "tmp_4_fu_397_p3");
    sc_trace(mVcdFile, tmp_fu_380_p3, "tmp_fu_380_p3");
    sc_trace(mVcdFile, tmp_8_fu_411_p3, "tmp_8_fu_411_p3");
    sc_trace(mVcdFile, zext_ln114_fu_418_p1, "zext_ln114_fu_418_p1");
    sc_trace(mVcdFile, zext_ln110_1_fu_365_p1, "zext_ln110_1_fu_365_p1");
    sc_trace(mVcdFile, add_ln114_fu_422_p2, "add_ln114_fu_422_p2");
    sc_trace(mVcdFile, tmp_5_fu_444_p3, "tmp_5_fu_444_p3");
    sc_trace(mVcdFile, tmp_6_fu_451_p3, "tmp_6_fu_451_p3");
    sc_trace(mVcdFile, or_ln110_3_fu_458_p2, "or_ln110_3_fu_458_p2");
    sc_trace(mVcdFile, or_ln110_4_fu_464_p2, "or_ln110_4_fu_464_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

max_pool_32_8_s::~max_pool_32_8_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void max_pool_32_8_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten21_reg_122 = add_ln97_reg_483.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten21_reg_122 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_145 = select_ln99_reg_593.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_145 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        m_0_reg_133 = select_ln110_1_reg_551.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        m_0_reg_133 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        x_0_reg_156 = select_ln110_3_reg_563.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_0_reg_156 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        y_0_reg_167 = y_reg_588.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        y_0_reg_167 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        add_ln97_reg_483 = add_ln97_fu_196_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_fu_190_p2.read(), ap_const_lv1_0))) {
        add_ln99_reg_546 = add_ln99_fu_344_p2.read();
        and_ln110_reg_504 = and_ln110_fu_234_p2.read();
        icmp_ln99_reg_493 = icmp_ln99_fu_208_p2.read();
        m_reg_488 = m_fu_202_p2.read();
        or_ln110_reg_536 = or_ln110_fu_327_p2.read();
        select_ln110_2_reg_514 = select_ln110_2_fu_252_p3.read();
        select_ln110_7_reg_530 = select_ln110_7_fu_319_p3.read();
        select_ln110_reg_499 = select_ln110_fu_214_p3.read();
        trunc_ln110_reg_520 = trunc_ln110_fu_272_p1.read();
        x_reg_509 = x_fu_240_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln97_reg_479 = icmp_ln97_fu_190_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0))) {
        or_ln110_2_reg_578 = or_ln110_2_fu_405_p2.read();
        output_addr_reg_583 =  (sc_lv<4>) (zext_ln114_1_fu_428_p1.read());
        zext_ln110_reg_556 = zext_ln110_fu_356_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0))) {
        select_ln110_1_reg_551 = select_ln110_1_fu_350_p3.read();
        select_ln110_3_reg_563 = select_ln110_3_fu_360_p3.read();
        select_ln99_reg_593 = select_ln99_fu_438_p3.read();
        y_reg_588 = y_fu_433_p2.read();
    }
}

void max_pool_32_8_s::thread_add_ln114_fu_422_p2() {
    add_ln114_fu_422_p2 = (!zext_ln114_fu_418_p1.read().is_01() || !zext_ln110_1_fu_365_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln114_fu_418_p1.read()) + sc_biguint<6>(zext_ln110_1_fu_365_p1.read()));
}

void max_pool_32_8_s::thread_add_ln97_fu_196_p2() {
    add_ln97_fu_196_p2 = (!ap_const_lv10_1.is_01() || !ap_phi_mux_indvar_flatten21_phi_fu_126_p4.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(ap_phi_mux_indvar_flatten21_phi_fu_126_p4.read()));
}

void max_pool_32_8_s::thread_add_ln99_fu_344_p2() {
    add_ln99_fu_344_p2 = (!ap_const_lv6_1.is_01() || !ap_phi_mux_indvar_flatten_phi_fu_149_p4.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(ap_phi_mux_indvar_flatten_phi_fu_149_p4.read()));
}

void max_pool_32_8_s::thread_and_ln110_fu_234_p2() {
    and_ln110_fu_234_p2 = (icmp_ln101_fu_228_p2.read() & xor_ln110_fu_222_p2.read());
}

void max_pool_32_8_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void max_pool_32_8_s::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void max_pool_32_8_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pool_32_8_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void max_pool_32_8_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_32_8_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln97_fu_190_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void max_pool_32_8_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_ap_phi_mux_indvar_flatten21_phi_fu_126_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten21_phi_fu_126_p4 = add_ln97_reg_483.read();
    } else {
        ap_phi_mux_indvar_flatten21_phi_fu_126_p4 = indvar_flatten21_reg_122.read();
    }
}

void max_pool_32_8_s::thread_ap_phi_mux_indvar_flatten_phi_fu_149_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_149_p4 = select_ln99_reg_593.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_149_p4 = indvar_flatten_reg_145.read();
    }
}

void max_pool_32_8_s::thread_ap_phi_mux_m_0_phi_fu_137_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_m_0_phi_fu_137_p4 = select_ln110_1_reg_551.read();
    } else {
        ap_phi_mux_m_0_phi_fu_137_p4 = m_0_reg_133.read();
    }
}

void max_pool_32_8_s::thread_ap_phi_mux_x_0_phi_fu_160_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_x_0_phi_fu_160_p4 = select_ln110_3_reg_563.read();
    } else {
        ap_phi_mux_x_0_phi_fu_160_p4 = x_0_reg_156.read();
    }
}

void max_pool_32_8_s::thread_ap_phi_mux_y_0_phi_fu_171_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_y_0_phi_fu_171_p4 = y_reg_588.read();
    } else {
        ap_phi_mux_y_0_phi_fu_171_p4 = y_0_reg_167.read();
    }
}

void max_pool_32_8_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_icmp_ln101_fu_228_p2() {
    icmp_ln101_fu_228_p2 = (!ap_phi_mux_y_0_phi_fu_171_p4.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_y_0_phi_fu_171_p4.read() == ap_const_lv3_4);
}

void max_pool_32_8_s::thread_icmp_ln97_fu_190_p2() {
    icmp_ln97_fu_190_p2 = (!ap_phi_mux_indvar_flatten21_phi_fu_126_p4.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten21_phi_fu_126_p4.read() == ap_const_lv10_200);
}

void max_pool_32_8_s::thread_icmp_ln99_fu_208_p2() {
    icmp_ln99_fu_208_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_149_p4.read().is_01() || !ap_const_lv6_10.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_149_p4.read() == ap_const_lv6_10);
}

void max_pool_32_8_s::thread_input_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            input_r_address0 =  (sc_lv<6>) (tmp_1_fu_369_p5.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            input_r_address0 =  (sc_lv<6>) (tmp_s_fu_298_p5.read());
        } else {
            input_r_address0 = "XXXXXX";
        }
    } else {
        input_r_address0 = "XXXXXX";
    }
}

void max_pool_32_8_s::thread_input_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<6>) (tmp_3_fu_388_p4.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            input_r_address1 =  (sc_lv<6>) (tmp_2_fu_333_p4.read());
        } else {
            input_r_address1 = "XXXXXX";
        }
    } else {
        input_r_address1 = "XXXXXX";
    }
}

void max_pool_32_8_s::thread_input_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_input_r_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        input_r_ce1 = ap_const_logic_1;
    } else {
        input_r_ce1 = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_m_fu_202_p2() {
    m_fu_202_p2 = (!ap_const_lv6_1.is_01() || !ap_phi_mux_m_0_phi_fu_137_p4.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(ap_phi_mux_m_0_phi_fu_137_p4.read()));
}

void max_pool_32_8_s::thread_or_ln110_1_fu_184_p2() {
    or_ln110_1_fu_184_p2 = (shl_ln110_fu_178_p2.read() | ap_const_lv3_1);
}

void max_pool_32_8_s::thread_or_ln110_2_fu_405_p2() {
    or_ln110_2_fu_405_p2 = (tmp_4_fu_397_p3.read() | tmp_fu_380_p3.read());
}

void max_pool_32_8_s::thread_or_ln110_3_fu_458_p2() {
    or_ln110_3_fu_458_p2 = (tmp_5_fu_444_p3.read() | tmp_6_fu_451_p3.read());
}

void max_pool_32_8_s::thread_or_ln110_4_fu_464_p2() {
    or_ln110_4_fu_464_p2 = (or_ln110_3_fu_458_p2.read() | or_ln110_2_reg_578.read());
}

void max_pool_32_8_s::thread_or_ln110_5_fu_246_p2() {
    or_ln110_5_fu_246_p2 = (and_ln110_fu_234_p2.read() | icmp_ln99_fu_208_p2.read());
}

void max_pool_32_8_s::thread_or_ln110_6_fu_266_p2() {
    or_ln110_6_fu_266_p2 = (shl_ln110_1_fu_260_p2.read() | ap_const_lv3_1);
}

void max_pool_32_8_s::thread_or_ln110_fu_327_p2() {
    or_ln110_fu_327_p2 = (shl_ln110_2_fu_276_p2.read() | ap_const_lv3_1);
}

void max_pool_32_8_s::thread_output_r_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        output_r_address0 = output_addr_reg_583.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        output_r_address0 =  (sc_lv<4>) (zext_ln114_1_fu_428_p1.read());
    } else {
        output_r_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void max_pool_32_8_s::thread_output_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_output_r_d0() {
    output_r_d0 = esl_bitset<32,32,7,1>(output_r_q0.read(), zext_ln110_reg_556.read(), or_ln110_4_fu_464_p2.read());
}

void max_pool_32_8_s::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln97_reg_479.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void max_pool_32_8_s::thread_select_ln110_1_fu_350_p3() {
    select_ln110_1_fu_350_p3 = (!icmp_ln99_reg_493.read()[0].is_01())? sc_lv<6>(): ((icmp_ln99_reg_493.read()[0].to_bool())? m_reg_488.read(): m_0_reg_133.read());
}

void max_pool_32_8_s::thread_select_ln110_2_fu_252_p3() {
    select_ln110_2_fu_252_p3 = (!or_ln110_5_fu_246_p2.read()[0].is_01())? sc_lv<3>(): ((or_ln110_5_fu_246_p2.read()[0].to_bool())? ap_const_lv3_0: ap_phi_mux_y_0_phi_fu_171_p4.read());
}

void max_pool_32_8_s::thread_select_ln110_3_fu_360_p3() {
    select_ln110_3_fu_360_p3 = (!and_ln110_reg_504.read()[0].is_01())? sc_lv<3>(): ((and_ln110_reg_504.read()[0].to_bool())? x_reg_509.read(): select_ln110_reg_499.read());
}

void max_pool_32_8_s::thread_select_ln110_4_fu_282_p3() {
    select_ln110_4_fu_282_p3 = (!icmp_ln99_fu_208_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln99_fu_208_p2.read()[0].to_bool())? ap_const_lv3_0: shl_ln110_fu_178_p2.read());
}

void max_pool_32_8_s::thread_select_ln110_5_fu_290_p3() {
    select_ln110_5_fu_290_p3 = (!and_ln110_fu_234_p2.read()[0].is_01())? sc_lv<3>(): ((and_ln110_fu_234_p2.read()[0].to_bool())? shl_ln110_1_fu_260_p2.read(): select_ln110_4_fu_282_p3.read());
}

void max_pool_32_8_s::thread_select_ln110_6_fu_311_p3() {
    select_ln110_6_fu_311_p3 = (!icmp_ln99_fu_208_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln99_fu_208_p2.read()[0].to_bool())? ap_const_lv3_1: or_ln110_1_fu_184_p2.read());
}

void max_pool_32_8_s::thread_select_ln110_7_fu_319_p3() {
    select_ln110_7_fu_319_p3 = (!and_ln110_fu_234_p2.read()[0].is_01())? sc_lv<3>(): ((and_ln110_fu_234_p2.read()[0].to_bool())? or_ln110_6_fu_266_p2.read(): select_ln110_6_fu_311_p3.read());
}

void max_pool_32_8_s::thread_select_ln110_fu_214_p3() {
    select_ln110_fu_214_p3 = (!icmp_ln99_fu_208_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln99_fu_208_p2.read()[0].to_bool())? ap_const_lv3_0: ap_phi_mux_x_0_phi_fu_160_p4.read());
}

void max_pool_32_8_s::thread_select_ln99_fu_438_p3() {
    select_ln99_fu_438_p3 = (!icmp_ln99_reg_493.read()[0].is_01())? sc_lv<6>(): ((icmp_ln99_reg_493.read()[0].to_bool())? ap_const_lv6_1: add_ln99_reg_546.read());
}

void max_pool_32_8_s::thread_shl_ln110_1_fu_260_p2() {
    shl_ln110_1_fu_260_p2 = (!ap_const_lv3_1.is_01())? sc_lv<3>(): x_fu_240_p2.read() << (unsigned short)ap_const_lv3_1.to_uint();
}

void max_pool_32_8_s::thread_shl_ln110_2_fu_276_p2() {
    shl_ln110_2_fu_276_p2 = (!ap_const_lv3_1.is_01())? sc_lv<3>(): select_ln110_2_fu_252_p3.read() << (unsigned short)ap_const_lv3_1.to_uint();
}

void max_pool_32_8_s::thread_shl_ln110_fu_178_p2() {
    shl_ln110_fu_178_p2 = (!ap_const_lv3_1.is_01())? sc_lv<3>(): ap_phi_mux_x_0_phi_fu_160_p4.read() << (unsigned short)ap_const_lv3_1.to_uint();
}

void max_pool_32_8_s::thread_tmp_1_fu_369_p5() {
    tmp_1_fu_369_p5 = esl_concat<61,3>(esl_concat<60,1>(esl_concat<58,2>(ap_const_lv58_0, trunc_ln110_reg_520.read()), ap_const_lv1_0), select_ln110_7_reg_530.read());
}

void max_pool_32_8_s::thread_tmp_2_fu_333_p4() {
    tmp_2_fu_333_p4 = esl_concat<61,3>(esl_concat<58,3>(ap_const_lv58_0, or_ln110_fu_327_p2.read()), select_ln110_5_fu_290_p3.read());
}

void max_pool_32_8_s::thread_tmp_3_fu_388_p4() {
    tmp_3_fu_388_p4 = esl_concat<61,3>(esl_concat<58,3>(ap_const_lv58_0, or_ln110_reg_536.read()), select_ln110_7_reg_530.read());
}

void max_pool_32_8_s::thread_tmp_4_fu_397_p3() {
    tmp_4_fu_397_p3 = (!zext_ln110_fu_356_p1.read().is_01() || sc_biguint<7>(zext_ln110_fu_356_p1.read()).to_uint() >= 32)? sc_lv<1>(): input_r_q1.read().range(sc_biguint<7>(zext_ln110_fu_356_p1.read()).to_uint(), sc_biguint<7>(zext_ln110_fu_356_p1.read()).to_uint());
}

void max_pool_32_8_s::thread_tmp_5_fu_444_p3() {
    tmp_5_fu_444_p3 = (!zext_ln110_reg_556.read().is_01() || sc_biguint<7>(zext_ln110_reg_556.read()).to_uint() >= 32)? sc_lv<1>(): input_r_q0.read().range(sc_biguint<7>(zext_ln110_reg_556.read()).to_uint(), sc_biguint<7>(zext_ln110_reg_556.read()).to_uint());
}

void max_pool_32_8_s::thread_tmp_6_fu_451_p3() {
    tmp_6_fu_451_p3 = (!zext_ln110_reg_556.read().is_01() || sc_biguint<7>(zext_ln110_reg_556.read()).to_uint() >= 32)? sc_lv<1>(): input_r_q1.read().range(sc_biguint<7>(zext_ln110_reg_556.read()).to_uint(), sc_biguint<7>(zext_ln110_reg_556.read()).to_uint());
}

void max_pool_32_8_s::thread_tmp_8_fu_411_p3() {
    tmp_8_fu_411_p3 = esl_concat<3,2>(select_ln110_2_reg_514.read(), ap_const_lv2_0);
}

void max_pool_32_8_s::thread_tmp_fu_380_p3() {
    tmp_fu_380_p3 = (!zext_ln110_fu_356_p1.read().is_01() || sc_biguint<7>(zext_ln110_fu_356_p1.read()).to_uint() >= 32)? sc_lv<1>(): input_r_q0.read().range(sc_biguint<7>(zext_ln110_fu_356_p1.read()).to_uint(), sc_biguint<7>(zext_ln110_fu_356_p1.read()).to_uint());
}

void max_pool_32_8_s::thread_tmp_s_fu_298_p5() {
    tmp_s_fu_298_p5 = esl_concat<61,3>(esl_concat<60,1>(esl_concat<58,2>(ap_const_lv58_0, trunc_ln110_fu_272_p1.read()), ap_const_lv1_0), select_ln110_5_fu_290_p3.read());
}

void max_pool_32_8_s::thread_trunc_ln110_fu_272_p1() {
    trunc_ln110_fu_272_p1 = select_ln110_2_fu_252_p3.read().range(2-1, 0);
}

void max_pool_32_8_s::thread_x_fu_240_p2() {
    x_fu_240_p2 = (!ap_const_lv3_1.is_01() || !select_ln110_fu_214_p3.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(select_ln110_fu_214_p3.read()));
}

void max_pool_32_8_s::thread_xor_ln110_fu_222_p2() {
    xor_ln110_fu_222_p2 = (icmp_ln99_fu_208_p2.read() ^ ap_const_lv1_1);
}

void max_pool_32_8_s::thread_y_fu_433_p2() {
    y_fu_433_p2 = (!ap_const_lv3_1.is_01() || !select_ln110_2_reg_514.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(select_ln110_2_reg_514.read()));
}

void max_pool_32_8_s::thread_zext_ln110_1_fu_365_p1() {
    zext_ln110_1_fu_365_p1 = esl_zext<6,3>(select_ln110_3_fu_360_p3.read());
}

void max_pool_32_8_s::thread_zext_ln110_fu_356_p1() {
    zext_ln110_fu_356_p1 = esl_zext<7,6>(select_ln110_1_fu_350_p3.read());
}

void max_pool_32_8_s::thread_zext_ln114_1_fu_428_p1() {
    zext_ln114_1_fu_428_p1 = esl_zext<64,6>(add_ln114_fu_422_p2.read());
}

void max_pool_32_8_s::thread_zext_ln114_fu_418_p1() {
    zext_ln114_fu_418_p1 = esl_zext<6,5>(tmp_8_fu_411_p3.read());
}

void max_pool_32_8_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_fu_190_p2.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln97_fu_190_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

